### ISSUE TITLE
Evaluar uso de grunt para juntar archivos js

### ISSUE THREAD

**Issue by aculquicondor** [aculquicondor/restaurante_mesas#107]
#103

**Comment by rudygodoy** [comment]
Lo acabo de configurar y funciona el concat, pero todavía estoy viendo como se podría integrar con el proyecto, ya que usa `npm` para instalar las dependencias y nosotros estamos usando `bower`.

**Comment by aculquicondor** [comment]
Me parece que sí se puede con `bower`

**Comment by aculquicondor** [comment]
http://www.nitinh.com/2013/05/getting-started-with-grunt-bower/ pues ambos
requieren npm hehe

**Comment by rudygodoy** [comment]
Sí, osea `npm` es el manejador de paquetes. Lo que estoy viendo es como mantener ambos en paralelo, hice más o menos lo mismo que indica el artículo hasta ahora y funciono normal.
Más tarde hago el commit.

**Comment by aculquicondor** [comment]
:+1:

**Comment by rasdan** [comment]
Hay un plugin para grunt para manejar las dependencias de bower https://www.npmjs.com/package/grunt-bower-install :)

**Comment by rudygodoy** [comment]
@alculquicondor ya hice commit del Gruntfile.js.js (así se tiene que llamar). Funciona el plugin concat, pero hay que instalarlo aparte. Vamos a usar `npm` nomas para instalar las dependencias de grunt en el `packages.json`. Lo hago ahora y con eso cerramos el ticket.

@rasdan ese plugin ya no funciona, su reemplazo es `grunt-wiredep`. De todas maneras sirve para inyectar los JS, y otros, en HTML, que también necesitamos, pero lo que quería ahora es manejar las dependencias para cuando alguien nuevo quiera usar grunt.

**Comment by aculquicondor** [comment]
closed #103
