### ISSUE TITLE
Crear Document User

### ISSUE THREAD

**Issue by rudygodoy** [aculquicondor/restaurante_mesas#14]
Integrar FOSUserBundle con el ODM para la gestión de usuarios y autenticación.

https://github.com/FriendsOfSymfony/FOSUserBundle

Tiempo estimado: 5 horas

**Comment by aculquicondor** [comment]
Esto se convertirá luego en privilegios, así que primero estoy leyendo sobre autenticación con Oauth, que es lo más adecuado para una API.

http://blog.tankist.de/blog/2013/07/16/oauth2-explained-part-1-principles-and-terminology/
