### ISSUE TITLE
Crear pruebas de unidad para modelos

### ISSUE THREAD

**Issue by rudygodoy** [aculquicondor/restaurante_mesas#17]
Crear pruebas de unidad para modelos (Order, Table, Store). Con los siguientes pasos:
* Crear
* Insertar
* Verificar Id
* Eliminar

OrderItem va como parte de Order (embed). Se debe probar insertar y borrar en una orden existente.

Tiempo estimado: 5 horas

**Comment by aculquicondor** [comment]
Mover ejecución de pruebas a otra base de datos

**Comment by rudygodoy** [comment]
Merged. Queda pendiente unificar las pruebas para usar los repositorios.
