### ISSUE TITLE
Documentar modelos creados

### ISSUE THREAD

**Issue by rudygodoy** [aculquicondor/restaurante_mesas#18]
Documentar atributos de modelos creados que corresponden a nuestro módulo en el wiki.

### Mesa (`Table`) 
- Id (`id`)
- Disponibilidad (`available`)
- Tiempo de ocupación (`occupation_time`)
- Capacidad (`capacity`)

Tiempo estimado: 2 horas

**Comment by aculquicondor** [comment]
Usa 3 #
A parte coloca los módulos

**Comment by aculquicondor** [comment]
Resuelto https://github.com/aculquicondor/restaurante_mesas/wiki/Modelos
