### ISSUE TITLE
Implementar pruebas de unidad para interfaces REST

### ISSUE THREAD

**Issue by rudygodoy** [aculquicondor/restaurante_mesas#32]
Implementar pruebas de unidad para interfaces REST.

**Comment by rudygodoy** [comment]
No todas las entidades tienen repositorios, por no ser parte de nuestro módulo. Integraremos pruebas de repositorios el próximo sprint.

**Comment by aculquicondor** [comment]
Sigo sin entender por qué necesitamos testear los repositorios si la idea es testear los modelos (que persistan y ya). Cada repositorio ya tiene su propio test.
