### ISSUE TITLE
Implementar interfaces REST para OrderItem

### ISSUE THREAD

**Issue by rudygodoy** [aculquicondor/restaurante_mesas#38]
Implementar interfaces REST (crear, actualizar, eliminar, leer) para entidad OrderItem.

**Comment by rudygodoy** [comment]
@Ajax11 lo mismo que en #42, sincroniza tu branch con `master` antes de hacer el PR. Estos dos tickets ya tienen 3 semanas, por favor completado antes de la reunión del martes o avísanos si necesitas ayuda.

**Comment by aculquicondor** [comment]
@rudygodoy este también se cierra? si es así coloca el PR

**Comment by rudygodoy** [comment]
@alculquicondor todavía, cuando lo termine envío el PR.
