### ISSUE TITLE
Migrar tipos de `timestamp` a `date`

### ISSUE THREAD

**Issue by aculquicondor** [aculquicondor/restaurante_mesas#44]
Leí que `timestamp` es un tipo interno de mongo que no debería usarse. Además, el ODM no está soportando bien las consultas tipo `$gt` `$lt` para `timestamp`.

**Comment by rudygodoy** [comment]
Revisar las implementaciones para identificar si ya se completo la migración a `Date`. Si falta alguna hacer el cambio.

**Comment by aculquicondor** [comment]
Verificar los phpdocs

**Comment by Ajax11** [comment]
Arreglado los phpdocs en el commit 7ddc0d51844c00d1b9563326104b6c1cda2d0db0
