### ISSUE TITLE
Crear modelo de datos entidad ítem-orden

### ISSUE THREAD

**Issue by rudygodoy** [aculquicondor/restaurante_mesas#7]
Crear modelo de datos para la entidad item-orden de acuerdo al diseño especificado en la fotografía.

**Comment by aculquicondor** [comment]
Esto no debería manejarse con la desnormalización?

**Comment by aculquicondor** [comment]
Sí es necerio implementar la clase para poder ser usada en #6 según http://doctrine-mongodb-odm.readthedocs.org/en/latest/reference/embedded-mapping.html

**Comment by rudygodoy** [comment]
@rasdan hice un OrderItem incompleto. Unelo con el que haz creado y usa ese nombre que ya está como referencia en Order.
