### ISSUE TITLE
Implementar Interfaz de listar mesas

### ISSUE THREAD

**Issue by aculquicondor** [aculquicondor/restaurante_mesas#89]

**Comment by aculquicondor** [comment]
@rasdan ?

**Comment by rasdan** [comment]
Si @alculquicondor dime

**Comment by aculquicondor** [comment]
vi que solo hay código de prueba, no las mesas que vienen del backend... nos queda solo una semana :(

**Comment by rasdan** [comment]
Si bro ntp en estos días lo termino.
