### ISSUE TITLE
Investigar Frameworks Frontend

### ISSUE THREAD

**Issue by aculquicondor** [aculquicondor/restaurante_mesas#92]
Opciones:
- AngularJS
- ReactJS
- Semantic UI

Preferible: modular, rutas.

Límite: 11 de Junio

**Comment by rasdan** [comment]
https://www.polymer-project.org

**Comment by aculquicondor** [comment]
Para cada framework, busca así: Single Page App

https://www.polymer-project.org/0.5/articles/spa.html

**Comment by aculquicondor** [comment]
Otra por aquí: http://backbonejs.org/

**Comment by rudygodoy** [comment]
Ya muchas opciones :)

**Comment by aculquicondor** [comment]
@rasdan ?

**Comment by rasdan** [comment]
AngularJS creo, estuve leyendo Polymer pero no hay mucha doc.

**Comment by rasdan** [comment]
Estoy integrando los assets en una branch.

**Comment by aculquicondor** [comment]
Ya, queda en Angular entonces? Todo dentro de la carpeta `web` no te
olvides... Cierra el issue si consideras decidido y abre el otro referido a
la estructura

**Comment by rudygodoy** [comment]
Se acordo usar Angular.
